server:
  address: ":8080" # 我们用一个新的端口 8080，避免和旧服务冲突

logger:
  level: "debug"
  stdout: true

mysql:
  link: "root:123456@tcp(127.0.0.1:3307)/go-rag?charset=utf8mb4&parseTime=True&loc=Local"

es:
  endpoints:
    - "http://127.0.0.1:9200"
  username: ""
  password: ""

model:
  embedding:
    provider: "openai"
    name: "text-embedding-3-small"
    endpoint: ""
    api_key: "YOUR_API_KEY" # 稍后我们会处理这里
  llm:
    provider: "openai"
    name: "gpt-3.5-turbo"
    endpoint: ""
    api_key: "YOUR_API_KEY" # 稍后我们会处理这里